config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  resources :notes
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    
    # binding.pry
    if current_user
      @notes = current_user.notes
      if params[:search].present?
        @notes = @notes.where('title LIKE ?', "%#{params[:search]}%")
      end
      @notes = @notes.paginate(page: params[:page], per_page: 6)
    else 
      redirect_to new_user_session_path
    end
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate(auth_options)
    
    if resource.nil?
      if User.exists?(email: params[:user][:email])
        flash[:alert] = "Invalid email or password."
      else
        flash[:alert] = "Please enter a valid credentials."
      end
      redirect_to new_user_session_path
    else
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      redirect_to after_sign_in_path_for(resource)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">Notes App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to 'Notes App', notes_path, class: 'nav-link ative fw-bold' %>
        </li>
      </ul>
      <form class="d-flex" role="search" method="get" action="<%= notes_path %>">
        <input class="form-control me-2" type="search" name="search" value="<%= params[:search] %>" placeholder="Search by title" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav ms-auto">
        <!-- Authentication Links -->
        <% if user_signed_in? %>
          <%# <li class="nav-item">
            <a class="nav-link" href="#">Upload</a>
          </li> %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
              <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item', form: { class: 'd-inline' } %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

app/views/notes/_form.html.erb
<div class="container-fluid">
    <%= form_with(model: note) do |form| %>
      <% if note.errors.any? %>
        <div style="color: red">
          <ul>
            <% note.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :title, style: "display: block", class: 'mt-1 mb-1' %>
        <%= form.text_field :title %>
      </div>

      <div>
        <%= form.label :content, style: "display: block",class: "mt-1 mb-1" %>
        <%= form.text_area :content, style: "width: 50%; height: 20%" %>
      </div>

      <div>
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>

      <div>
        <%= form.submit class: 'btn btn-primary'%>
      </div>
    <% end %>
</div>

app/views/notes/_note.html.erb
<div class="container border justify-content-center">
  <div class="card col-sm-4">
    <div class="card-body">
      <div class="text-center h2">
        <%= note.title %>
      </div>
      <hr>
      <div>
        <%= note.content %>
      </div>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="container card mt-2 p-2">
    <div class="text-center h2 bg-secondary rounded p-1">Editing Note</div>

    <%= render "form", note: @note %>

    <br>

    <div class="d-flex justify-content-between">
      <%= link_to "Show", @note,class: 'btn btn-primary' %> 
      <%= link_to "Back", notes_path,class: 'btn btn-primary' %>
    </div>
</div>

app/views/notes/index.html.erb
<% if notice %>
  <div class="container">
    <p style="color: green" class="text-center border border-success rounded p-2 mt-2">
      <%= notice %>
    </p>
  </div>
<% end %>
<div class="container-fluid mt-2">
  <div class="mt-2 mb-3 text-center">
    <%= link_to "New Note", new_note_path, class: 'btn btn-outline-primary' %>
  </div>
  <div class="row justify-content-center">
    <% @notes.each do |note| %>
      <div class="col-sm-6 col-lg-4 d-flex justify-content-around">
        <div class="card mb-4" style="width: 22rem; height: 12rem;" id="note-<%= note.id %>">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-center"><%= note.title %></h5>
            <p class="card-text"><%= truncate(note.content, length: 100) %></p>

            <div class="mt-auto d-flex justify-content-between">
              <a href="<%= note_path(note) %>" class="btn btn-primary btn-sm mx-1">View</a>
              <a href="<%= edit_note_path(note) %>" class="btn btn-secondary btn-sm mx-1">Edit</a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

    <!-- Pagination Controls -->
  <div class="fixed-bottom">
    <div class="pagination justify-content-center mt-4">
      <%= will_paginate @notes %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container card mt-2 p-2">
    <div class="text-center h2 bg-secondary rounded p-1">New note</div>

    <%= render "form", note: @note %>
    <br>

    <div class="d-flex justify-content-between">
      <%= link_to "Back", notes_path, class: 'btn btn-primary' %>
    </div>
</div>

app/views/notes/show.html.erb
<% if notice %>
  <div class="container">
    <p style="color: green" class="text-center border border-success rounded p-2 mt-2">
      <%= notice %>
    </p>
  </div>
<% end %>
<div class="container justify-content-center mt-2">
  <div class="card">
    <div class="card-body">
      <div class="text-center h2">
        <%= @note.title %>
      </div>
      <hr>
      <div class="bg-secondary text-white p-2 rounded">
        <%= @note.content %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between pt-5">
    <%= link_to "Edit", edit_note_path(@note), class: 'btn btn-primary' %>
    <%= link_to "Back", notes_path, class: 'btn btn-primary' %>
    <%= button_to "Delete", @note, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>